### ISSUE TITLE
Weed out old addons not compatible with firefox quantum

### ISSUE THREAD

**Issue by allo-** [allo-/firefox-profilemaker#105]
As support for firefox 56 and 52esr ended, the incompatible addons should be removed.

On the site the other addons can be upgraded to a current version. I do not know if the update from an incompatible version installed via the profile maker will be possible.

**Comment by StarPicard** [comment]
As I understand the current process of including the addons is a manual copy in this project. Would it be possible to download the addons directly from the source when generating the zip-folder. 
This way the user will always have the newest version...

**Comment by allo-** [comment]
This would need some download and caching mechanism, which is probably too complicated. A server side cron job may be a better option. Both would need to make sure the URL stays the same. Personally I think the addons should be updated after the first run anyway because the user cannot know how fresh the addon file is.

And the scope of this bug is actually to remove the "legacy" addons and replace them by webextension versions if there is no updated version of the addon.

I am not fully sure when they should be removed, because waterfox wants to keep the old API and the profile generator probably works there as well.
As the old API currently allows more privacy extensions it may be worth to keep them as option for waterfox users.

**Comment by StarPicard** [comment]
Seems a bit tricky, anyway it would not be my way to install some add-ons from a third party.
Don't get me wrong, but including a profile.js file to my Firefox profile is not as risky as including add-ons from an external source for me. So my way would be to simply install them on first run...

**Comment by allo-** [comment]
No need to worry, Mozilla enforces signature from addons.mozilla.org since quite some time.
You cannot even distribute your own addon if you don't let Mozilla sign it.

**Comment by StarPicard** [comment]
Oh, okay I see. This has been there for quite some time. But at this time Mozilla has lost me to Chromium... But good news even if I hear them three years later.
