### ISSUE TITLE
Disable Pocket completely

### ISSUE THREAD

**Issue by StarPicard** [allo-/firefox-profilemaker#107]
Hello, it would be nice to have an option to disable Pocket completely.
The prefs.js part woult be:
`user_pref("extensions.pocket.enabled", false);`

Thank you for this great website!

By the way, would it be possible to add a field for own entrys in the prefs.js?
Something like an textarea to add own prefs...

**Comment by allo-** [comment]
For the merging, there is Bug #25, which probably should be a textfield on the last page.
