### ISSUE TITLE
Include some settings from harden.it

### ISSUE THREAD

**Issue by StarPicard** [allo-/firefox-profilemaker#113]
Hello, I would like to take a look at harden.it and try to add some features from there.
Alternatively it might be possible to integrate #85 and only choose the Security Level from Harden.it

What do you think?

**Comment by allo-** [comment]
The discussion about a common format got us to an interesting format, which as far as I know none of the two projects is using ;-).

Integrating features from them is useful just as all other good lists of settings. I welcome more pull requests :-).

**Comment by allo-** [comment]
I close here now.
Please create specific issues for different settings or create pull-requests. Tracking a large list of possible settings in a single bug is not useful.
