### ISSUE TITLE
New profile based on kuketz-blog.de

### ISSUE THREAD

**Issue by StarPicard** [allo-/firefox-profilemaker#116]
Hey, I would like to create a new profile based on the "[Firefox Kompendium](https://www.kuketz-blog.de/firefox-ein-browser-fuer-datenschutzbewusste-firefox-kompendium-teil1/)" of [Mike Kuketz](https://www.kuketz-blog.de/).

I'm not sure if you know him or can read German, but he is very focused on privacy. However, this would need the implementation of some new add-ons. Though this article season is still in progress I do not know which will be necessary in the end, but I want to ask if you're open for this.

**Comment by allo-** [comment]
Yes, I can read german and know his blog. Let's keep this bug tracker english, so more people can contribute.

I am open for new profiles with other defaults than the main profile. The current "private browsing" profile is more a placeholder for other more interesting profiles. But are you sure this needs an own profile? I think Mike Kuketz has quite similar goals in his articles as the default profile has.

When you want to create a larger amount of settings, I would recommend to try to get the app running in an own test server. Have a look at the [installation guide](https://github.com/allo-/firefox-profilemaker/blob/master/INSTALL.md) and tell me if something isn't correct anymore.

**Comment by StarPicard** [comment]
Hello, sorry for long off-time, but I have had some trouble.
Currently I don't have the time to start a test server, but maybe I would take this some time later.

With this "Kuketz-Profile" I thought it could be with the addons he is recommending in his blog articles about Firefox.

**Comment by allo-** [comment]
You do not need a test server as in hardware, but it is helpful to run "./manage.sh runserver" for the project in a virtualenv when developing. Its enough to run this on your own pc and test on localhost.

Of course you can write json files without any tests, but its harder to get them right then.

Anyway, I am willing to merge settings files and deploy a kuketz-profile (maybe it would be nice to have a more neutral name) if it is reasonable. I am not sure if your planned additions won't just fit in the default profile, as the aim of the project is pretty much the same as what kuketz wants to do in his article series.

**Comment by StarPicard** [comment]
My vision is to implement a profile orientated on his article series. This means, only enabling the add-ons he  is recommending and so on.

I just have a thought in my mind if it might be possible to launch a thread in his new forum and get to a community cooperation. But that's just a brainwave, I don't know how you think of it.

**Comment by allo-** [comment]
Please feel free to create settings and profile json files or open issues for settings we do not include yet. I close here for now.
