### ISSUE TITLE
Disabling IndexedDB breaks sites

### ISSUE THREAD

**Issue by allo-** [allo-/firefox-profilemaker#135]
IndexedDB seems to become more and more important for different websites, like e.g. GMail (https://github.com/allo-/firefox-profilemaker/issues/130#issuecomment-419700161) and needs a bigger warning and possibly another default value

**Comment by allo-** [comment]
More and more reports are coming in, the default should probably be changed.

**Comment by tjbenator** [comment]
Figured out that this breaks the twitter.com login page too. It appears that once you login, IndexedDB can be re-enabled.

**Comment by allo-** [comment]
Twitter is complicated. Disabling (all) cookies even breaks reading tweets, because you get an infinite redirect loop.

I wonder if we should change the setting to "not disabled" in the default profile and maybe refer to some addons that deletes browser storages, that can be added in the addons section.

As Mozilla unified the storage cleanup APIs, there could even be "Cookie" cleaners, that work for IndexedDB / localstorage.

**Comment by allo-** [comment]
It seems, that Mozilla has removed the option to disable indexedDB and introduced some bugs when ``dom.indexedDB.enabled`` is set to false.
I close here now. Bug #166 can be used for discussing the alternatives.
