### ISSUE TITLE
Extend disable pocket functionality

### ISSUE THREAD

**Issue by M0r13n** [allo-/firefox-profilemaker#138]
Personally I always disable the following settings beside the one that are already in 'pocket.json'

browser.newtabpage.activity-stream.section.highlights.includePocket : false
extensions.pocket.api : blank
extensions.pocket.oAuthConsumerKey : blank
extensions.pocket.site : blank

Those settings could be beneficial, because even if Pocket would try to communicate with its servers, it simply cant.

**Comment by allo-** [comment]
Thank you, but https://github.com/allo-/firefox-profilemaker/blob/master/settings/pocket.json already includes ``browser.newtabpage.activity-stream.section.highlights.includePocket``.

I do not think we need to change the other settings. It makes it only harder for people to turn it back on and I did not yet see that any off-switch required further actions like removing configurable URLs.
