### ISSUE TITLE
Addon: Cookie Autodelete

### ISSUE THREAD

**Issue by cookiengineer** [allo-/firefox-profilemaker#143]
I wanted to ask whether it is possible or not to add the extension [Cookie Autodelete](https://github.com/Cookie-AutoDelete/Cookie-AutoDelete) to the Firefox Profilemaker?

This extension has served me well, and what I really like about this extension is the cookie deletion by-default; except the ones that are whitelisted. Usually medium and other websites have an insane amount of cookies, and this extensions lets them store cookies as long as the tab is open. When the tab is closed, they are automatically deleted; except the whitelisted ones that are allowed to last "forever".

It kind of makes a perfect complementary to uMatrix, as uMatrix is great for blocking stuff, but doesn't handle the case well when there's a website requiring all kinds of tracking cookies in order to get rid of those damn overlay popups. Especially when you're from the EU :-(

**Comment by allo-** [comment]
Since it is the replacement for self destructing cookies, I think it should be added.

**Comment by cookiengineer** [comment]
Awesome <3
