### ISSUE TITLE
Firefox is placing ads on the new tab page

### ISSUE THREAD

**Issue by allo-** [allo-/firefox-profilemaker#148]
Source: https://www.cyberciti.biz/web-developer/firefox-is-now-placing-ads-and-here-is-how-to-disable-it/
About:config Key: TODO

**Comment by Atavic** [comment]
Called snippets. Mozilla told that it was a temporary experiment (due to many articles and discussions rising) but they are made by

> Mozilla Marketing and Operations Team

and

> run by Mozilla Lifecycle Marketing Team 

See: https://snippets.mozilla.com/

^ an admin login page for Mozilla partners.

**Comment by allo-** [comment]
So is this completely removed or will it come back in some form?

**Comment by Atavic** [comment]
Absolutely not removed, even the old [wiki](https://wiki.mozilla.org/Websites/Snippets), created at the time of Mozilla *Org*, has no End of Life listed. Wiki Mozilla is dying because Mozilla *Corp* cares nothing about mantaining those info pages.

**Comment by Atavic** [comment]
> Mozilla told that it was a temporary experiment 

They lied out of the unexpected reactions.

**Comment by allo-** [comment]
This should be resolved by the settings for the new tab page and Firefox view
