### ISSUE TITLE
Sessionstore by site

### ISSUE THREAD

**Issue by ajay-gh** [allo-/firefox-profilemaker#156]
Setting recommended:
browser.sessionstore.privacy_level = 2

Title: Do not store extra session data
Description: This preference controls when to store extra information about a session including contents of forms, scrollbar positions, cookies, and POST data. Session data could be used for fingerprinting. Meaning of values:
    0 = Store extra session data for any site. (Default starting with Firefox 4.)
    1 = Store extra session data for unencrypted (non-HTTPS) sites only. (Default before Firefox 4.)
    2 = Never store extra session data.
Few secure sites do require session data (=0) to function properly.

See https://http://kb.mozillazine.org/Browser.sessionstore.privacy_level
for more details.

**Comment by mattia-b89** [comment]
related to: #264

**Comment by allo-** [comment]
This was implemented in eff9ab0ab9b37bab26c77b317057e6988702af28. For further discussion see #264
