### ISSUE TITLE
please check for correctness 

### ISSUE THREAD

**Issue by ajay-gh** [allo-/firefox-profilemaker#158]
When selecting the switch "disable TLS session identifiers" on the website (meaning the check-mark is visible), the corresponding line in the generated prefs.je reads: security.ssl.disable_session_identifiers=false

I cannot find a proper reference kb at mozilla. Could you please check that this is not a mistake or a typo ? '...disable...' set to false sounds to me like 'enable'. 
Thanks

**Comment by allo-** [comment]
You're right. Thank you for catching this mistake.
