### ISSUE TITLE
Profile with extensions makes Firefox 69 unusable

### ISSUE THREAD

**Issue by wesaphzt** [allo-/firefox-profilemaker#173]
First of all, thanks for the great site.

I've come across an issue when using a profile that has extensions. Navigating to a site results in tab crash and extensions show in the toolbar but aren't usable.

Seems to be the pref extensions.autoDisableScopes causing the issue and removing it solves it although you have to manually re-enable the extensions on first start.

Not sure if it's something that's changed in 69 or if it's a bug in the release.

**Comment by wesaphzt** [comment]
Unfortunately I've no idea why it's broken or what's happened.
I just upgraded the browser, tried to use a profile and it was borked so I managed to narrow the issue down to that preference.
As far as I can see it's basically a security policy for which addons and from where can be enabled or updated.
I've tried using different values for extensions.autoDisableScopes but same issue.
Removing the pref is a good workaround even if inconvenient to re-enable extensions again.
Hopefully others can also check and confirm the issue.

**Comment by allo-** [comment]
Can you test again, with a profile without the canvas blocker extension? For me it is fixed, when CanvasBlocker is not installed. I removed it for now from the Addon list, but I would like you to verify that it works for you, too.

I guess it is some kind of Firefox bug, maybe because of the new extension permission system not granting all needed permissions to preinstalled addons or something similar.

**Comment by allo-** [comment]
I created a bug at CanvasBlocker upstream asking for help to find the issue. Maybe this is a Firefox bug, let's see what the CanvasBlocker developers tell us.

https://github.com/kkapsner/CanvasBlocker/issues/399

**Comment by wesaphzt** [comment]
That's strange, the initial profile config I had issues with didn't even have the CanvasBlocker extension in it, so it can't be that.
It's not the most recently generated profile but I can't imagine it changes too much over time.
Had the same issue with a newly generated profile but didn't test without CanvasBlocker and that's not an option on the site now unless you can attach a profile with it here?

**Comment by allo-** [comment]
Can you try enabling IndexedDB?

**Comment by allo-** [comment]
I reported a Bug in the Mozilla Bugtracker: https://bugzilla.mozilla.org/show_bug.cgi?id=1581384

**Comment by allo-** [comment]
I suppose it is time to stop disabling IndexedDB. Extensions like Stylish or greasemonkey need it for storing their data, Firefox-Tabs crash when it is disabled (see https://www.reddit.com/r/ffprofile/comments/9eq0kc/crashing_youtube_tab/ as well).

Personally I am annoyed by it, but it seems to be breaking too much. I changed the default value for IndexedDB. The description already contains warnings against potential problems and tab crashes, so it is reasonable that a profile should not disable it by default.

**Comment by wesaphzt** [comment]
Yes, seems others disable it as well, reports that uBlock needs it(??).
The annoying thing is everything worked fine prior to 69 (just the core privacy extensions).
Anyway, thanks for finding the cause and fixing it.

**Comment by allo-** [comment]
Another related setting is usercontext/container tabs. Some addons seem to be confused, when their data is stored in the wrong context.
This may especially affect addons using indexeddb and localstorage to store their data.

**Comment by allo-** [comment]
In reply to: https://github.com/kkapsner/CanvasBlocker/issues/399#issuecomment-531592516 

Is it Firefox 69 specific? We already had reports about crashing YouTube tabs when IndexedDB is disabled one year ago: https://www.reddit.com/r/ffprofile/comments/9eq0kc/crashing_youtube_tab/

**Comment by allo-** [comment]
It seems, that Mozilla has removed the option to disable indexedDB and introduced some bugs when ``dom.indexedDB.enabled`` is set to false.
I close here now. Bug #166 can be used for discussing the alternatives.
