### ISSUE TITLE
Setting "network.trr.mode=5" on Firefox ESR does not work

### ISSUE THREAD

**Issue by chris-est** [allo-/firefox-profilemaker#174]
I created a profile and imported to Firefox 60.9.0esr (current version in debian stable).

Firefox does not load any website, as DOH was introduced in > v60 and the DNS resolver does not seem to work with this setting.

Setting **network.trr.mode=0** (instead of =5) solves this.
I guess a hint somewhere on ffprofile.com would be nice for users of the Firefox ESR Version so others know where to look?

**Comment by allo-** [comment]
I am not sure, if 0 will be set to another value, https://wiki.mozilla.org/Trusted_Recursive_Resolver#network.trr.mode seems to imply that it is the default and may be changed by Mozilla, when 5 is an explicit opt-out.

I wonder why 60esr breaks with this setting, when it does not know DoH at all.

I change it to 0 on the live site, but keep it as 5 in the repo for now, so it will be reverted in the future. 68esr is scheduled for 2019-10-22 anyway (https://wiki.mozilla.org/Release_Management/Calendar)

**Comment by chris-est** [comment]
I agree, 5 should be the value to set.
That's why i suggested the warning only. Also i wanted to document this, so maybe other users would find it here and figure out faster why firefox does not open any webpage.

**Comment by allo-** [comment]
I guess setting it to 5 when 60esr is EOL would be sufficent.

When I see how governments are opposing DoH, I am no longer sure if blocking DoH is right either. I hope there will be more (and more privacy friendly) DoH server soon and maybe we can then add a choice between different trustworthy DoH servers.

**Comment by allo-** [comment]
The website now sets ``network.trr.mode=5`` again.
