### ISSUE TITLE
Disable URL-Bar Changes in Firefox 75

### ISSUE THREAD

**Issue by allo-** [allo-/firefox-profilemaker#186]
https://lifehacker.com/how-to-disable-firefox-75s-new-address-bar-1842728031

    browser.urlbar.openViewOnFocus
    browser.urlbar.update1
    browser.urlbar.update1.interventions
    browser.urlbar.update1.searchTips

**Comment by Hrxn** [comment]
Not really an annoyance, in my opinion.

**Comment by allo-** [comment]
I did not use it more than a few minutes yet, so I added this primarily as a reminder what the settings are.

I think we're getting enough stuff for a "look & feel" section or similar, but I would like to split this to another profile.

**Comment by allo-** [comment]
The settings will probably be removed soon. On reddit a developer said the nightlys do not contain the old address bar anymore. So it will probably not be useful to add this.

Waiting on: A firefox release that is based on todays nightlys (76? 77?)

**Comment by allo-** [comment]
Here is a script to patch your Firefox installation:

https://github.com/SebastianSimon/firefox-selection-fix

It works fine, but cannot be integrated into the website, because it works in another way than the profile generator.
