### ISSUE TITLE
Chrome parity

### ISSUE THREAD

**Issue by Madis0** [allo-/firefox-profilemaker#191]
Some options that provide parity with Chrome:

* [Write "Not Secure" on HTTP pages](https://bugzilla.mozilla.org/show_bug.cgi?id=1335970) - **security.insecure_connection_text.enabled** = true
* [Disable backspace as "go back" action](http://kb.mozillazine.org/Browser.backspace_action) - **browser.backspace_action** = 2
* [SameSite=lax cookies (postponed in Chrome)](https://bugzilla.mozilla.org/show_bug.cgi?id=1604212) - **network.cookie.sameSite.laxByDefault** = true

**Comment by allo-** [comment]
I think this are three kinds of settings. 

The backspace_action seems to be 2 by default.

Please add the "Not Secure" suggestion as comment to #112 and open an own bug for the same site cookies.
