### ISSUE TITLE
DoH providers

### ISSUE THREAD

**Issue by Madis0** [allo-/firefox-profilemaker#193]
DoH encrypts the DNS requests, so it should be encouraged to _enable_ it, not disable.
If you don't like Cloudflare, it is better to just create a dropdown option of various providers, such as [privacytools.io's](https://www.privacytools.io/providers/dns/).

**Comment by allo-** [comment]
This is quite a controversial topic. There are several serious issues with using DoH (I think you will find enough places with discussions about this).

As the default is to use a specific DNS and we would have to provide trusted alternatives (who should decide which are trusted?) the current best recommendation seems to be to turn it off and use the system configured DNS.

You are still able not to use the option and configure a trusted provider.

**Comment by allo-** [comment]
An option to configure a provider could be useful. I would not know which one to recommend.

And I still wonder if DNS-over-TLS (outside the browser) wouldn't be the better option.

**Comment by FrittenLoverMarvin** [comment]
Yes, an option outside the browsers might be better. I am unsure too.
