### ISSUE TITLE
Disable Screenshots

### ISSUE THREAD

**Issue by Madis0** [allo-/firefox-profilemaker#195]
I don't need it and I doubt I am the only one ¯\\\_(ツ)_/¯

**extensions.screenshots.disabled** = true

**Comment by allo-** [comment]
It's already there: https://github.com/allo-/firefox-profilemaker/blob/master/settings/screenshot.json

**Comment by Madis0** [comment]
Huh, cannot find it on the site.

**Comment by allo-** [comment]
Indeed, it seems to be missing in the profile file.

**Comment by allo-** [comment]
Added it.

**Comment by Madis0** [comment]
I see it now, but that's not what I suggested anyway. I suggested disabling the whole Screenshots feature, like it is possible to disable Pocket.

**Comment by allo-** [comment]
Hmm, maybe. I think pocket is more intrusive, but screenshots are an addition nobody asked for, too. So this is probably something that should get an own category as well.

**Comment by edisondotme** [comment]
> It's already there: https://github.com/allo-/firefox-profilemaker/blob/master/settings/screenshot.json
Mozilla [removed cloud uploads for screenshots](https://www.ghacks.net/2018/10/04/mozilla-plans-to-change-confusing-screenshot-tool-terminology/) so this can be removed entirely.
