### ISSUE TITLE
Google Meet dosen't work while using profile!

### ISSUE THREAD

**Issue by pog5** [allo-/firefox-profilemaker#222]
I can't use google meet while using the profile that i downloaded from ffprofile.com (used defaults)

**Comment by pog5** [comment]
all i get is a white screen with the error sound

**Comment by allo-** [comment]
The report is pretty meaningless without information what options you are using.

The site tries to explain what every option does, so you can try to find which ones may affect it.

My guess: Have a look at ...
- WebRTC related things
- IndexedDB

The systematic method: Disable options until Google Meet works again. Many options are probably irrelevant, like, for example, disabling pocket, but many others affect modern web applications as the techniques that can be abused for tracking were introduced for such apps like Google Meet.

You can also try to have a look into the web console if Google Meet logs anything useful, what may give a hint which feature shouldn't be disabled when one wants to use Google Meet.

**Comment by pog5** [comment]
I unticked 
    WebRTC related things
    IndexedDB
and it now works, thanks!

**Comment by pog5** [comment]
I unticked 
    WebRTC related things
    IndexedDB
and it now works, thanks!
