### ISSUE TITLE
Add link to https://ffprofile.com/

### ISSUE THREAD

**Issue by alexislefebvre** [allo-/firefox-profilemaker#227]
Hello,
https://ffprofile.com/ brought me here but I don't see links from that repo to https://ffprofile.com/

Could it be added?

**Comment by allo-** [comment]
The reason why it is not there is, that the idea of the project was to build something usable for self-hosting.

But probably most people are using the site. The question is if someone sees the github repo and does not know that there is a running instance.

**Comment by onkoe** [comment]
While it may only help someone once in a blue moon, a link could help people find the GitHub page faster. So +1!
