### ISSUE TITLE
'Containerise' addon may be a relevant addition

### ISSUE THREAD

**Issue by xcasxcursex** [allo-/firefox-profilemaker#231]
[Containerise](https://github.com/kintesh/containerise) Allows you to make [rulesets ](https://github.com/shvchk/containerise-lists)which ensure certain pages always open in certain containers. Perhaps you'll also find this useful.

**Comment by allo-** [comment]
Thank you. The bug for containerize addons is #141 and there are quite a few implementations that are worth considering. Feel free to add to the thread there.
