### ISSUE TITLE
Disable webaudio API breaks discord

### ISSUE THREAD

**Issue by msirringhaus** [allo-/firefox-profilemaker#242]
I've been using ffprofile for a long time now, and as of today it breaks Discord (the webapp doesn't start but says it unexpectedly crashed).
With some trial and error approach, I nailed it down to "Disable webaudio API". If I enable it, Discord works again.
Not sure what to do about it, but I figured filing this issue will help other people who might have the same problem.

**Comment by allo-** [comment]
What does it break? everything? Or just the audio function? For the second I guess some generic hint "May break audio chats" would be useful, as it probably breaks any modern voice chat.

**Comment by msirringhaus** [comment]
Everything. The app doesn't even start.

**Comment by allo-** [comment]
Sadly I can reproduce. Maybe someone likes to complain on Discord's feedback site about it. If you still like to disable the API, it's probably worth trying to use an user agent script of a browser that Discord doesn't recognize as supporting webaudio.
