### ISSUE TITLE
I created a profile but using ffprofile.com not sure which setting is blocking the detection of light/dark theme preference.

### ISSUE THREAD

**Issue by Jieiku** [allo-/firefox-profilemaker#253]
I created a profile but using ffprofile.com not sure which setting is blocking the detection of light/dark theme preference.

I already tried disabling ALL extensions and restarting firefox but problem persists, sites that normally detect your theme preference no longer are, and simple display as white, such as this very github page.

If I can figure out which setting caused it I will post back.

**Comment by allo-** [comment]
My best guess: Try to remove `privacy.resistFingerprinting`. It is breaking all kind of things in exchange for bringing a lot of tor-browser features to Firefox.

Otherwise we don't have settings that are related to light/dark mode, yet.  
I wonder if this may indeed leak 1 bit of information.

**Comment by Jieiku** [comment]
Thanks, going to try removing that and will report back!
