### ISSUE TITLE
Privacy Settings Update

### ISSUE THREAD

**Issue by g-monk** [allo-/firefox-profilemaker#48]
I just commented this on another project based on Privacy on FireFox and I am doing the same here. I am not an expert coder, just a beginner. However, I saw in the project that when a user finishes the configuration, the .js file lacks the following settings. These settings are suggested on by Privacytools.io and I think they add more to your script project. 

; Disable WebRTC 
user_pref(media.peerconnection.turn.disable, true)
user_pref(media.peerconnection.use_document_iceservers, false)
user_pref(media.peerconnection.video.enabled, false)
user_pref(media.peerconnection.identity.timeout, 1)

; Privacy Enhancements

user_pref(privacy.trackingprotection.enabled, true)
user_pref(geo.enabled, false)
user_pref(browser.safebrowsing.enabled, false)
user_pref(browser.safebrowsing.malware.enabled, false)
user_pref(dom.event.clipboardevents.enabled, false)
user_pref(network.cookie.cookieBehavior, 1)
user_pref(network.cookie.lifetimePolicy, 2)
user_pref(browser.cache.offline.enable, false)
user_pref(browser.send_pings, false)
user_pref(webgl.disabled, true)
user_pref(dom.battery.enabled, false)
user_pref(browser.sessionstore.max_tabs_undo, 0)

**Comment by allo-** [comment]
looks to me, like most stuff is already available in the project.

For the settings not included yet, like ´´tab_undo´´ see for example #43. This is a feature, which doesn't increase your security against websites but only against other users of the browser, like the private browsing mode does. This can be useful, but when we have profiles and create such a "private browsing" profile.

For the rest, please check https://github.com/allo-/firefox-profilemaker/blob/master/forms.py if it isn't already included and then open an issue per topic. This allows to discuss this special feature, come to a good title and description for the option and stay clear what is done and what isn't.
Huge dumps of "this are good settings" options are hard to work with, as they always need to be split by topic, checked for duplicates, checked for usefulness (will this be an useful default, is this an option which is useful to be shown in the default profile, etc.) and then added with description.

**Comment by allo-** [comment]
By the way, we have a wiki, with a lot of settings links here: https://github.com/allo-/firefox-profilemaker/wiki

What's there and not included needs exactly this work: Find out, how it is useful, provide a title, a short description (posibbly with links to explanations of the option) and a reasonable default value. Then it's easy to add. If you want to, you can even try to look at the ``forms.py`` and write it in this format. But when the values are clear from an issue, it's no problem for me to translate it to the correct format for you. Analysing the options is the harder task.

**Comment by allo-** [comment]
I close here now. When you have new settings, please create one issue per topic (this often even means one per setting), so they can easily be closed when it's implemented.
