### ISSUE TITLE
Default user agent option breaks Firefox rich text editor

### ISSUE THREAD

**Issue by mx8s** [allo-/firefox-profilemaker#54]
Hi,

I used your site and I have a comment about the following option:
**Privacy>Fake another Useragent**
When keeping this blank (which I did) you generate the following string: `user_pref("general.useragent.override", "");`
I found out that this seem to cause the Firefox rich text editor to not work anymore. See screenshots:
http://imgur.com/a/wiuEd  (with the string used).
http://imgur.com/a/j7z9v  (without the string used).

Anyway, keep up the good work.

**Comment by allo-** [comment]
This is a bug. Blank should not generate ANY config line

**Comment by allo-** [comment]
Fixed in 09181267db84c4840bdfad9862397e026844c734.

You can test on the ffprofile.com site. An empty input should not not generate a fake useragent at all.
