### ISSUE TITLE
Social media integration

### ISSUE THREAD

**Issue by allo-** [allo-/firefox-profilemaker#68]
https://gist.github.com/haasn/69e19fc2fe0e25f3cff5#social-media-integration

social.directories=""
social.whitelist=""
social.manifest.facebook=""
social.remote-install.enabled=false
social.toast-notifications.enabled=false

**Comment by StarPicard** [comment]
Social API is deprecated: [https://bugzilla.mozilla.org/buglist.cgi?bug_id=1388902,1406193 ](https://bugzilla.mozilla.org/buglist.cgi?bug_id=1388902,1406193 )

**Comment by allo-** [comment]
I think this is obsolete then.
