### ISSUE TITLE
Offline Modus (maybe addon related)

### ISSUE THREAD

**Issue by CHEF-KOCH** [allo-/firefox-profilemaker#7]
Hello, thanks for your project, maybe an offline-modus would be nice, because you need already an Browser to visit the page but maybe someone installed his OS clean and want to start new. So there are possible security problems, since he need to use other Browsers.

I would be thankful for an Online/Offline or Addon solution, since there exist no solution which handles all aspects.

**Comment by allo-** [comment]
For something which works completely without browser, this is the wrong project. It is not useful to add a GUI of some kind here, but maybe the data about settings will be usable for other projects, when it's refactored.

I am thinking about generating the options from a dict like:

```(python)
[
{
"name": "privacy setting",
"config": [{"privacy": true, "spyonme": false}],
"addons": ["addonpath.xpi", "addonpath2.xpi"]
}
]
```

Such a format could be used by other tools. Tell me, if you are interested in actually doing something like this, then we can agree on some format and i focus a bit more on separating the stuff soon.

The current solution is to use your fresh profile to generate a new one. Then you can delete the current profile and unzip the generated one. You may run the generator locally by starting a django project and installing this app there. it needs almost no configuration and works fine with ``./manage.py startserver`` (single threaded testserver).

**Comment by rrooij** [comment]
This is a minor issue in my opinion. Even if there was a desktop application with the exact same functionality, it would still require people to go on the internet to download it. Unless you deploy it on the computer in some way. But if you would do the latter, you could also just generate it on an already 'secure' computer and copy the profile over.

**Comment by allo-** [comment]
I close the issue, as this is an webapp, which will never have a desktop GUI.
