### ISSUE TITLE
Disable google analytics on the addons page

### ISSUE THREAD

**Issue by allo-** [allo-/firefox-profilemaker#87]
https://github.com/mozilla/addons-frontend/issues/2785
https://bugzilla.mozilla.org/show_bug.cgi?id=1302552
https://github.com/mozilla/addons-frontend/issues/1107

Find a way to reliably disable Google Analytics one the about:addons page.
Seems like old (restartless) extensions work there, but new webextensions do not. So using uBlock for this is no option as they will need to upgrade to webextensions, when mozilla removes the APIs for more powerful extensions.

**Comment by allo-** [comment]
extensions.webservice.discoverURL may help.

**Comment by Thorin-Oakenpants** [comment]
kill the url and hide the panel - make users visit AMO directly

```js
user_pref("extensions.getAddons.showPane", false); // hidden pref
user_pref("extensions.webservice.discoverURL", "");
```

**Comment by allo-** [comment]
Implemented an hour ago in https://github.com/allo-/firefox-profilemaker/commit/83f30880cef509043da1f48d26d97de0e3e85d7e ;-)
