### ISSUE TITLE
Improved Design

### ISSUE THREAD

**Issue by allo-** [allo-/firefox-profilemaker#89]
The website could use some nice design.
Help wanted from people, who know how to create good designs.

**Comment by plungingChode** [comment]
I tried my best with #214 .

**Comment by allo-** [comment]
I need to take a closer look before saying more about it.

Maybe you can post a screenshot for now so I can get a first impression?

**Comment by plungingChode** [comment]
Sure thing, here it is:
![image](https://user-images.githubusercontent.com/45334856/98451513-923f9580-2146-11eb-8407-02f50965dea5.png)

It's currently using the default select/text input elements, but I plan to change that to custom ones (as with the checkbox widget).
![image](https://user-images.githubusercontent.com/45334856/98451550-f3ffff80-2146-11eb-9b0e-9a8ea8dfd1ee.png)

**Comment by allo-** [comment]
This is great. The side bar looks very professional.

The checkboxes may be a bit too large (in relation to the text next to them), but this are details.
I am not sure about adding too many custom widgets. The check boxes may have an advantage because most native checkboxes are rather small, but I think for text fields and dropdown menus it's nice to have the native look.

**Comment by plungingChode** [comment]
The checkboxes are implemented, so that they can be resized by changing a single height/width pair in the CSS. And if the other widgets are not necessary, it's all the simpler for me.

**Comment by allo-** [comment]
I am not sure and you seem to know about design, so maybe the custom widgets would fit the design.
The details can be tweaked later and I will test it on my own. I just wanted the screenshots for a first impression.

**Comment by allo-** [comment]
I think this is implemented for quite a while. Closing this bug. Further development may happen for reducing scripts in #261.
