### ISSUE TITLE
Firefox 57?

### ISSUE THREAD

**Issue by knobhead** [allo-/firefox-profilemaker#92]
Hi, stumbled upon this nice project.

I'd like to start off with a fresh and proper Firefox profile once FF 57 is released (due november).

As FF57 comes with a lot of fundamental changes, most notable the drop of legacy/non-WebExtension add-ons, I was wondering if there's any plans or activities to adapt the ffprofile.com service to the new firefox version.
Or do you plan to wait until it has reached stable and adapt ffprofile.com later this year?

Regards

**Comment by allo-** [comment]
The good news: The profile generator will just keep working unlike extensions which modify settings.

This said, there is work to do for configuring webextensions like #41. This will need support for json addon configs and possibly sqlite on the long term.
Some of the addons and planned addons (like CTR) will not work. uBlock and privacybadger are ported, quite a few other privacy extensions will not exist anymore at all.

I will not upgrade directly to 57, but watch the shitstorm when everybody loses his extensions and wait if mozilla will change things or if a fork with chances to stay current and secure will emerge. I probably will test 57 and further versions to see when and if I should upgrade, but as I will wait to use it I will not know all new options which may be useful.

Pull requests and settings (https://github.com/allo-/firefox-profilemaker/wiki/Contribute-Settings) are always welcome and can easily be merged. And please see the help-wanted label for where to contribute.

**Comment by allo-** [comment]
Looks like all addons but xclear (which was more a demo how to add addons when the function was new) are already compatible. Probably some of the addons proposed in other issues are not.
