### ISSUE TITLE
More telemetry settings

### ISSUE THREAD

**Issue by allo-** [allo-/firefox-profilemaker#94]
- toolkit.telemetry.newProfilePing.enabled
- toolkit.telemetry.shutdownPingSender.enabled
- Much information: https://firefox-source-docs.mozilla.org/toolkit/components/telemetry/telemetry/internals/preferences.html

**Comment by Atavic** [comment]
Enable the .../data/new profile ping 
Allow the shutdown ping to be sent when the browser shuts down

https://firefox-source-docs.mozilla.org/toolkit/components/telemetry/telemetry/internals/preferences.html

**Comment by allo-** [comment]
Thank you, good ressource.

**Comment by StarPicard** [comment]
Seems to be already integrated. (?)

**Comment by Atavic** [comment]
**FF55** and up:
user_pref("toolkit.telemetry.newProfilePing.enabled", false);

See:
https://github.com/ghacksuserjs/ghacks-user.js/blob/master/user.js#L183

It's under section:
/* 0330: disable telemetry

**Comment by allo-** [comment]
https://github.com/allo-/firefox-profilemaker/blob/master/settings/telemetry.json seems to be quite complete thanks to @StarPicard. If there are any new settings (newProfilePing is already included) open a new issue or just create a pull request (you can use the online editor on github for adding a new line quickly).
