### ISSUE TITLE
First Party Isolation

### ISSUE THREAD

**Issue by allo-** [allo-/firefox-profilemaker#95]
New in Firefox 57:
https://www.reddit.com/r/firefox/comments/6y7lpw/what_is_first_party_isolation_how_does_it_work/

**Comment by knobhead** [comment]
I understood this breaks extensions such as [Cookie AutoDelete](https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/) that might be worth including/offering in a Fx 57 flavour of firefox-profilemaker?

**Comment by allo-** [comment]
I am not sure how much this will break them (at least after the next updates), It probably just introduces more cookie jars, just like usercontexts. 

Firefox handles this a bit intransparent, which data stays and which is deleted when using usercontexts and similar things. When they will have a reasonable API for deleting cookies from the isolated cookie jars, extensions will probably adapt to it.

Until then its a trade-off: Simple security with isolation or using extensions like cookie autodelete and and similar to remove any cookie. If you block thirdparty cookies, there is no need for isolation anyway, as far as I understand the feature.

Are you currently tracking what settings need to be adapted to Fx 57? We could start a [profile](https://github.com/allo-/firefox-profilemaker/tree/master/profiles), if there are too much changes how to handle this.

**Comment by StarPicard** [comment]
#118

**Comment by allo-** [comment]
Merged.
